package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cloudboy-jh/bentotui/cmd/bento/logic"
)

// runInitCLI runs the init command in CLI mode.
func runInitCLI(args []string) {
	appName := ""
	if len(args) > 0 && args[0] != "--help" && args[0] != "-h" {
		appName = args[0]
	}
	if appName == "" {
		appName = "my-bento-app"
	}

	cfg := logic.ProjectConfig{
		AppName: appName,
	}

	fmt.Printf("Creating project: %s\n", cfg.AppName)
	created, err := logic.ScaffoldProject(cfg)
	if err != nil {
		fatal("%v", err)
	}

	fmt.Println()
	fmt.Println("Generated by bento init:")
	for _, f := range created {
		fmt.Printf("  - %s\n", f)
	}

	fmt.Println()
	fmt.Println("Starter imports BentoTUI runtime packages:")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/theme")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/registry/bricks/bar")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/registry/bricks/dialog")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/registry/bricks/input")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/registry/bricks/surface")
	fmt.Println("  - github.com/cloudboy-jh/bentotui/registry/rooms")

	fmt.Println()
	fmt.Println("You can do anything from here:")
	fmt.Printf("  - cd %s && go run .\n", cfg.AppName)
	fmt.Println("  - edit main.go directly (choose a room per page)")
	fmt.Println("  - run bento add <brick> to copy-and-own source when you want ownership")

	if _, err := os.Stat(filepath.Join(cfg.AppName, "go.sum")); err != nil {
		fmt.Println()
		fmt.Println("Note:")
		fmt.Println("  - go.sum was not created during scaffold")
		fmt.Println("  - run: go mod tidy")
	}
	fmt.Println("Done.")
}

// runAddCLI runs the add command in CLI mode.
func runAddCLI(args []string) {
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		printAddHelp()
		return
	}

	failures := 0
	for _, name := range args {
		fmt.Printf("Installing brick: %s\n", name)

		result := logic.InstallComponent(name)
		if result.Error != nil {
			fmt.Printf("  Error: %v\n", result.Error)
			failures++
			continue
		}

		for _, f := range result.Files {
			fmt.Printf("  Created: %s\n", f)
		}
		for _, f := range result.Skipped {
			fmt.Printf("  Skipped (exists): %s\n", f)
		}
	}

	if failures > 0 {
		fatal("%d brick(s) failed to install", failures)
	}
	fmt.Println("Done.")
}

// runListCLI runs the list command in CLI mode.
func runListCLI(args []string) {
	if len(args) > 0 && (args[0] == "--help" || args[0] == "-h") {
		printListHelp()
		return
	}

	fmt.Println("Available bricks:")
	for _, c := range logic.Registry() {
		fmt.Printf("  %-10s %s\n", c.Name, c.Desc)
	}
}

// runDoctorCLI runs the doctor command in CLI mode.
func runDoctorCLI(args []string) {
	fmt.Println("Running doctor checks...")
	report := logic.RunDoctor()

	for _, r := range report.Results {
		icon := "✓"
		if !r.Pass {
			icon = "✗"
		}
		if r.Note != "" && !r.Pass {
			fmt.Printf("  [%s] %s - %s\n", icon, r.Label, r.Note)
		} else {
			fmt.Printf("  [%s] %s\n", icon, r.Label)
		}
	}

	if report.AllPass {
		fmt.Println("All checks passed!")
	} else {
		fmt.Println("Some checks failed.")
		os.Exit(1)
	}
}

func printAddHelp() {
	fmt.Print(`Usage: bento add <brick> [brick...]

Copies source into bricks/<name>/ and are yours to modify.

Available bricks:
`)
	for _, c := range logic.Registry() {
		fmt.Printf("  %-10s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  bento add card")
	fmt.Println("  bento add input bar surface")
	fmt.Println("  bento add dialog")
	fmt.Println()
}

func printListHelp() {
	fmt.Print(`Usage: bento list

Shows available registry bricks with one-line descriptions.

Examples:
  bento list

`)
}
