package main

import (
	"fmt"
	"os"

	"github.com/cloudboy-jh/bentotui/cmd/bento/logic"
)

// runInitCLI runs the init command in CLI mode.
func runInitCLI(args []string) {
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		printInitHelp()
		return
	}
	if len(args) > 1 {
		fatal("usage: bento init <bento>")
	}

	name := args[0]
	fmt.Printf("Initializing bento template: %s\n", name)
	result := logic.InstallBento(name)
	if result.Error != nil {
		fatal("%v", result.Error)
	}

	fmt.Println()
	fmt.Println("Generated by bento init:")
	for _, f := range result.Files {
		fmt.Printf("  - %s\n", f)
	}

	fmt.Println()
	fmt.Printf("Run: cd %s && go run .\n", name)
	fmt.Println("Done.")
}

func printInitHelp() {
	fmt.Print(`Usage:
  bento init <bento>

Copies a full template app from registry/bentos into:
  - ./<bento>

Available bentos:
`)
	for _, c := range logic.BentoRegistry() {
		fmt.Printf("  %-20s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  bento init home-screen")
	fmt.Println("  bento init app-shell")
	fmt.Println()
	fmt.Println("Use 'bento list' to browse all bentos, bricks, and recipes.")
	fmt.Println()
}

// runAddCLI runs the add command in CLI mode.
func runAddCLI(args []string) {
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		printAddHelp()
		return
	}

	kind := "brick"
	names := args
	if args[0] == "recipe" {
		kind = "recipe"
		names = args[1:]
	}

	if len(names) == 0 {
		fatal("missing %s name", kind)
	}

	failures := 0
	for _, name := range names {
		fmt.Printf("Installing %s: %s\n", kind, name)

		result := installByKind(kind, name)
		if result.Error != nil {
			fmt.Printf("  Error: %v\n", result.Error)
			failures++
			continue
		}

		for _, f := range result.Files {
			fmt.Printf("  Created: %s\n", f)
		}
		for _, f := range result.Skipped {
			fmt.Printf("  Skipped (exists): %s\n", f)
		}
	}

	if failures > 0 {
		fatal("%d %s(s) failed to install", failures, kind)
	}
	fmt.Println("Done.")
}

// runListCLI runs the list command in CLI mode.
func runListCLI(args []string) {
	if len(args) > 0 && (args[0] == "--help" || args[0] == "-h") {
		printListHelp()
		return
	}

	fmt.Println("Available bricks:")
	for _, c := range logic.BrickRegistry() {
		fmt.Printf("  %-20s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Available recipes:")
	for _, c := range logic.RecipeRegistry() {
		fmt.Printf("  %-20s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Available bentos:")
	for _, c := range logic.BentoRegistry() {
		fmt.Printf("  %-20s %s\n", c.Name, c.Desc)
	}
}

// runDoctorCLI runs the doctor command in CLI mode.
func runDoctorCLI(args []string) {
	fmt.Println("Running doctor checks...")
	report := logic.RunDoctor()

	for _, r := range report.Results {
		icon := "✓"
		if !r.Pass {
			icon = "✗"
		}
		if r.Note != "" && !r.Pass {
			fmt.Printf("  [%s] %s - %s\n", icon, r.Label, r.Note)
		} else {
			fmt.Printf("  [%s] %s\n", icon, r.Label)
		}
	}

	if report.AllPass {
		fmt.Println("All checks passed!")
	} else {
		fmt.Println("Some checks failed.")
		os.Exit(1)
	}
}

func printAddHelp() {
	fmt.Print(`Usage:
  bento add <brick> [brick...]
  bento add recipe <name> [name...]

Copies source into:
  - bricks/<name>/   for bricks
  - recipes/<name>/  for recipes

Available bricks:
`)
	for _, c := range logic.BrickRegistry() {
		fmt.Printf("  %-10s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Available recipes:")
	for _, c := range logic.RecipeRegistry() {
		fmt.Printf("  %-20s %s\n", c.Name, c.Desc)
	}
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  bento add card")
	fmt.Println("  bento add input bar surface")
	fmt.Println("  bento add recipe filter-bar")
	fmt.Println()
}

func printListHelp() {
	fmt.Print(`Usage: bento list

Shows available bentos, bricks, and recipes with one-line descriptions.

Output is grouped by bricks, recipes, and bentos.

Examples:
  bento list

`)
}

func installByKind(kind, name string) logic.InstallResult {
	if kind == "recipe" {
		return logic.InstallRecipe(name)
	}
	return logic.InstallComponent(name)
}
