package theme

// presets is the registry of all built-in themes.
// Themes are plain value types — no global init, no validation, no side effects.
// Call Preset(name) to get one. Call Names() to list all available names.
var presets = map[string]Theme{
	"catppuccin-mocha":     catppuccinMocha(),
	"catppuccin-macchiato": catppuccinMacchiato(),
	"catppuccin-frappe":    catppuccinFrappe(),
	"dracula":              dracula(),
	"tokyo-night":          tokyoNight(),
	"tokyo-night-storm":    tokyoNightStorm(),
	"nord":                 nord(),
	"bento-rose":           bentoRose(),
	"gruvbox-dark":         gruvboxDark(),
	"monokai-pro":          monokaiPro(),
	"kanagawa":             kanagawa(),
	"rose-pine":            rosePine(),
	"ayu-mirage":           ayuMirage(),
	"one-dark":             oneDark(),
	"material-ocean":       materialOcean(),
	"github-dark":          githubDark(),
}

func catppuccinMocha() Theme {
	return &BaseTheme{
		ThemeName:                  "catppuccin-mocha",
		BackgroundColor:            h("#1e1e2e"),
		BackgroundPanelColor:       h("#313244"),
		BackgroundOverlayColor:     h("#292938"),
		BackgroundInteractiveColor: h("#45475a"),
		CardChromeColor:            h("#313244"),
		CardBodyColor:              h("#1e1e2e"),
		CardFrameFGColor:           h("#bac2de"),
		CardFocusEdgeColor:         h("#89b4fa"),
		TextColor:                  h("#cdd6f4"),
		TextMutedColor:             h("#6c7086"),
		TextInverseColor:           h("#1e1e2e"),
		TextAccentColor:            h("#89b4fa"),
		BorderNormalColor:          h("#313244"),
		BorderSubtleColor:          h("#181825"),
		BorderFocusColor:           h("#89b4fa"),
		SuccessColor:               h("#a6e3a1"),
		WarningColor:               h("#f9e2af"),
		ErrorColor:                 h("#f38ba8"),
		InfoColor:                  h("#89b4fa"),
		SelectionBGColor:           h("#89b4fa"),
		SelectionFGColor:           h("#1e1e2e"),
		InputBGColor:               h("#313244"),
		InputFGColor:               h("#cdd6f4"),
		InputPlaceholderColor:      h("#6c7086"),
		InputCursorColor:           h("#89b4fa"),
		InputBorderColor:           h("#89b4fa"),
		BarBGColor:                 h("#313244"),
		BarFGColor:                 h("#cdd6f4"),
		FooterBGColor:              h("#181825"),
		FooterFGColor:              h("#cdd6f4"),
		FooterMutedColor:           h("#6c7086"),
		DialogBGColor:              h("#292938"),
		DialogFGColor:              h("#cdd6f4"),
		DialogBorderColor:          h("#89b4fa"),
		DialogScrimColor:           h("#181825"),
	}
}

func catppuccinMacchiato() Theme {
	return &BaseTheme{
		ThemeName:                  "catppuccin-macchiato",
		BackgroundColor:            h("#24273a"),
		BackgroundPanelColor:       h("#363a4f"),
		BackgroundOverlayColor:     h("#2d3047"),
		BackgroundInteractiveColor: h("#494d64"),
		CardChromeColor:            h("#363a4f"),
		CardBodyColor:              h("#24273a"),
		CardFrameFGColor:           h("#b8c0e0"),
		CardFocusEdgeColor:         h("#8aadf4"),
		TextColor:                  h("#cad3f5"),
		TextMutedColor:             h("#6e738d"),
		TextInverseColor:           h("#24273a"),
		TextAccentColor:            h("#8aadf4"),
		BorderNormalColor:          h("#363a4f"),
		BorderSubtleColor:          h("#1e2030"),
		BorderFocusColor:           h("#8aadf4"),
		SuccessColor:               h("#a6da95"),
		WarningColor:               h("#eed49f"),
		ErrorColor:                 h("#ed8796"),
		InfoColor:                  h("#8aadf4"),
		SelectionBGColor:           h("#8aadf4"),
		SelectionFGColor:           h("#24273a"),
		InputBGColor:               h("#363a4f"),
		InputFGColor:               h("#cad3f5"),
		InputPlaceholderColor:      h("#6e738d"),
		InputCursorColor:           h("#8aadf4"),
		InputBorderColor:           h("#8aadf4"),
		BarBGColor:                 h("#363a4f"),
		BarFGColor:                 h("#cad3f5"),
		FooterBGColor:              h("#1e2030"),
		FooterFGColor:              h("#cad3f5"),
		FooterMutedColor:           h("#6e738d"),
		DialogBGColor:              h("#2d3047"),
		DialogFGColor:              h("#cad3f5"),
		DialogBorderColor:          h("#8aadf4"),
		DialogScrimColor:           h("#1e2030"),
	}
}

func catppuccinFrappe() Theme {
	return &BaseTheme{
		ThemeName:                  "catppuccin-frappe",
		BackgroundColor:            h("#303446"),
		BackgroundPanelColor:       h("#414559"),
		BackgroundOverlayColor:     h("#383c52"),
		BackgroundInteractiveColor: h("#51576d"),
		CardChromeColor:            h("#414559"),
		CardBodyColor:              h("#303446"),
		CardFrameFGColor:           h("#b5bfe2"),
		CardFocusEdgeColor:         h("#8caaee"),
		TextColor:                  h("#c6d0f5"),
		TextMutedColor:             h("#737994"),
		TextInverseColor:           h("#303446"),
		TextAccentColor:            h("#8caaee"),
		BorderNormalColor:          h("#414559"),
		BorderSubtleColor:          h("#292c3c"),
		BorderFocusColor:           h("#8caaee"),
		SuccessColor:               h("#a6d189"),
		WarningColor:               h("#e5c890"),
		ErrorColor:                 h("#e78284"),
		InfoColor:                  h("#8caaee"),
		SelectionBGColor:           h("#8caaee"),
		SelectionFGColor:           h("#303446"),
		InputBGColor:               h("#414559"),
		InputFGColor:               h("#c6d0f5"),
		InputPlaceholderColor:      h("#737994"),
		InputCursorColor:           h("#8caaee"),
		InputBorderColor:           h("#8caaee"),
		BarBGColor:                 h("#414559"),
		BarFGColor:                 h("#c6d0f5"),
		FooterBGColor:              h("#292c3c"),
		FooterFGColor:              h("#c6d0f5"),
		FooterMutedColor:           h("#737994"),
		DialogBGColor:              h("#383c52"),
		DialogFGColor:              h("#c6d0f5"),
		DialogBorderColor:          h("#8caaee"),
		DialogScrimColor:           h("#292c3c"),
	}
}

func dracula() Theme {
	return &BaseTheme{
		ThemeName:                  "dracula",
		BackgroundColor:            h("#282a36"),
		BackgroundPanelColor:       h("#44475a"),
		BackgroundOverlayColor:     h("#343746"),
		BackgroundInteractiveColor: h("#4d5068"),
		CardChromeColor:            h("#44475a"),
		CardBodyColor:              h("#282a36"),
		CardFrameFGColor:           h("#f8f8f2"),
		CardFocusEdgeColor:         h("#bd93f9"),
		TextColor:                  h("#f8f8f2"),
		TextMutedColor:             h("#6272a4"),
		TextInverseColor:           h("#282a36"),
		TextAccentColor:            h("#bd93f9"),
		BorderNormalColor:          h("#44475a"),
		BorderSubtleColor:          h("#21222c"),
		BorderFocusColor:           h("#bd93f9"),
		SuccessColor:               h("#50fa7b"),
		WarningColor:               h("#f1fa8c"),
		ErrorColor:                 h("#ff5555"),
		InfoColor:                  h("#8be9fd"),
		SelectionBGColor:           h("#bd93f9"),
		SelectionFGColor:           h("#282a36"),
		InputBGColor:               h("#44475a"),
		InputFGColor:               h("#f8f8f2"),
		InputPlaceholderColor:      h("#6272a4"),
		InputCursorColor:           h("#f8f8f2"),
		InputBorderColor:           h("#bd93f9"),
		BarBGColor:                 h("#44475a"),
		BarFGColor:                 h("#f8f8f2"),
		FooterBGColor:              h("#21222c"),
		FooterFGColor:              h("#f8f8f2"),
		FooterMutedColor:           h("#6272a4"),
		DialogBGColor:              h("#343746"),
		DialogFGColor:              h("#f8f8f2"),
		DialogBorderColor:          h("#bd93f9"),
		DialogScrimColor:           h("#21222c"),
	}
}

func tokyoNight() Theme {
	return &BaseTheme{
		ThemeName:                  "tokyo-night",
		BackgroundColor:            h("#1a1b26"),
		BackgroundPanelColor:       h("#24283b"),
		BackgroundOverlayColor:     h("#1f2335"),
		BackgroundInteractiveColor: h("#2f3549"),
		CardChromeColor:            h("#24283b"),
		CardBodyColor:              h("#1a1b26"),
		CardFrameFGColor:           h("#a9b1d6"),
		CardFocusEdgeColor:         h("#7aa2f7"),
		TextColor:                  h("#c0caf5"),
		TextMutedColor:             h("#565f89"),
		TextInverseColor:           h("#1a1b26"),
		TextAccentColor:            h("#7aa2f7"),
		BorderNormalColor:          h("#24283b"),
		BorderSubtleColor:          h("#16161e"),
		BorderFocusColor:           h("#7aa2f7"),
		SuccessColor:               h("#9ece6a"),
		WarningColor:               h("#e0af68"),
		ErrorColor:                 h("#f7768e"),
		InfoColor:                  h("#7aa2f7"),
		SelectionBGColor:           h("#7aa2f7"),
		SelectionFGColor:           h("#1a1b26"),
		InputBGColor:               h("#24283b"),
		InputFGColor:               h("#c0caf5"),
		InputPlaceholderColor:      h("#565f89"),
		InputCursorColor:           h("#7aa2f7"),
		InputBorderColor:           h("#7aa2f7"),
		BarBGColor:                 h("#24283b"),
		BarFGColor:                 h("#c0caf5"),
		FooterBGColor:              h("#16161e"),
		FooterFGColor:              h("#c0caf5"),
		FooterMutedColor:           h("#565f89"),
		DialogBGColor:              h("#1f2335"),
		DialogFGColor:              h("#c0caf5"),
		DialogBorderColor:          h("#7aa2f7"),
		DialogScrimColor:           h("#16161e"),
	}
}

func tokyoNightStorm() Theme {
	return &BaseTheme{
		ThemeName:                  "tokyo-night-storm",
		BackgroundColor:            h("#24283b"),
		BackgroundPanelColor:       h("#2f3549"),
		BackgroundOverlayColor:     h("#292e42"),
		BackgroundInteractiveColor: h("#3b4261"),
		CardChromeColor:            h("#2f3549"),
		CardBodyColor:              h("#24283b"),
		CardFrameFGColor:           h("#a9b1d6"),
		CardFocusEdgeColor:         h("#7aa2f7"),
		TextColor:                  h("#c0caf5"),
		TextMutedColor:             h("#565f89"),
		TextInverseColor:           h("#24283b"),
		TextAccentColor:            h("#7aa2f7"),
		BorderNormalColor:          h("#2f3549"),
		BorderSubtleColor:          h("#1d202f"),
		BorderFocusColor:           h("#7aa2f7"),
		SuccessColor:               h("#9ece6a"),
		WarningColor:               h("#e0af68"),
		ErrorColor:                 h("#f7768e"),
		InfoColor:                  h("#7aa2f7"),
		SelectionBGColor:           h("#7aa2f7"),
		SelectionFGColor:           h("#24283b"),
		InputBGColor:               h("#2f3549"),
		InputFGColor:               h("#c0caf5"),
		InputPlaceholderColor:      h("#565f89"),
		InputCursorColor:           h("#7aa2f7"),
		InputBorderColor:           h("#7aa2f7"),
		BarBGColor:                 h("#2f3549"),
		BarFGColor:                 h("#c0caf5"),
		FooterBGColor:              h("#1d202f"),
		FooterFGColor:              h("#c0caf5"),
		FooterMutedColor:           h("#565f89"),
		DialogBGColor:              h("#292e42"),
		DialogFGColor:              h("#c0caf5"),
		DialogBorderColor:          h("#7aa2f7"),
		DialogScrimColor:           h("#1d202f"),
	}
}

func nord() Theme {
	return &BaseTheme{
		ThemeName:                  "nord",
		BackgroundColor:            h("#2e3440"),
		BackgroundPanelColor:       h("#3b4252"),
		BackgroundOverlayColor:     h("#353c4a"),
		BackgroundInteractiveColor: h("#434c5e"),
		CardChromeColor:            h("#3b4252"),
		CardBodyColor:              h("#2e3440"),
		CardFrameFGColor:           h("#d8dee9"),
		CardFocusEdgeColor:         h("#88c0d0"),
		TextColor:                  h("#eceff4"),
		TextMutedColor:             h("#616e88"),
		TextInverseColor:           h("#2e3440"),
		TextAccentColor:            h("#88c0d0"),
		BorderNormalColor:          h("#3b4252"),
		BorderSubtleColor:          h("#242932"),
		BorderFocusColor:           h("#88c0d0"),
		SuccessColor:               h("#a3be8c"),
		WarningColor:               h("#ebcb8b"),
		ErrorColor:                 h("#bf616a"),
		InfoColor:                  h("#81a1c1"),
		SelectionBGColor:           h("#88c0d0"),
		SelectionFGColor:           h("#2e3440"),
		InputBGColor:               h("#3b4252"),
		InputFGColor:               h("#eceff4"),
		InputPlaceholderColor:      h("#616e88"),
		InputCursorColor:           h("#88c0d0"),
		InputBorderColor:           h("#88c0d0"),
		BarBGColor:                 h("#3b4252"),
		BarFGColor:                 h("#eceff4"),
		FooterBGColor:              h("#242932"),
		FooterFGColor:              h("#eceff4"),
		FooterMutedColor:           h("#616e88"),
		DialogBGColor:              h("#353c4a"),
		DialogFGColor:              h("#eceff4"),
		DialogBorderColor:          h("#88c0d0"),
		DialogScrimColor:           h("#242932"),
	}
}

func bentoRose() Theme {
	return &BaseTheme{
		ThemeName:                  "bento-rose",
		BackgroundColor:            h("#201a19"),
		BackgroundPanelColor:       h("#5f4843"),
		BackgroundOverlayColor:     h("#2f2422"),
		BackgroundInteractiveColor: h("#7a5d56"),
		CardChromeColor:            h("#3d2d2a"),
		CardBodyColor:              h("#5f4843"),
		CardFrameFGColor:           h("#f4ddca"),
		CardFocusEdgeColor:         h("#ff92b6"),
		TextColor:                  h("#f4ddca"),
		TextMutedColor:             h("#d5b8a2"),
		TextInverseColor:           h("#201a19"),
		TextAccentColor:            h("#ff92b6"),
		BorderNormalColor:          h("#b990a1"),
		BorderSubtleColor:          h("#a77b8f"),
		BorderFocusColor:           h("#ff92b6"),
		SuccessColor:               h("#9cd67a"),
		WarningColor:               h("#f1c56b"),
		ErrorColor:                 h("#ff7e9f"),
		InfoColor:                  h("#86b6ff"),
		SelectionBGColor:           h("#ff92b6"),
		SelectionFGColor:           h("#201a19"),
		InputBGColor:               h("#7a5d56"),
		InputFGColor:               h("#f4ddca"),
		InputPlaceholderColor:      h("#c5a791"),
		InputCursorColor:           h("#ff92b6"),
		InputBorderColor:           h("#b990a1"),
		BarBGColor:                 h("#5f4843"),
		BarFGColor:                 h("#f4ddca"),
		FooterBGColor:              h("#2f2422"),
		FooterFGColor:              h("#f4ddca"),
		FooterMutedColor:           h("#d5b8a2"),
		DialogBGColor:              h("#7a5d56"),
		DialogFGColor:              h("#f4ddca"),
		DialogBorderColor:          h("#b990a1"),
		DialogScrimColor:           h("#181312"),
	}
}

func gruvboxDark() Theme {
	return &BaseTheme{
		ThemeName:                  "gruvbox-dark",
		BackgroundColor:            h("#282828"),
		BackgroundPanelColor:       h("#3c3836"),
		BackgroundOverlayColor:     h("#32302f"),
		BackgroundInteractiveColor: h("#504945"),
		CardChromeColor:            h("#3c3836"),
		CardBodyColor:              h("#282828"),
		CardFrameFGColor:           h("#d5c4a1"),
		CardFocusEdgeColor:         h("#83a598"),
		TextColor:                  h("#ebdbb2"),
		TextMutedColor:             h("#928374"),
		TextInverseColor:           h("#282828"),
		TextAccentColor:            h("#83a598"),
		BorderNormalColor:          h("#3c3836"),
		BorderSubtleColor:          h("#1d2021"),
		BorderFocusColor:           h("#83a598"),
		SuccessColor:               h("#b8bb26"),
		WarningColor:               h("#fabd2f"),
		ErrorColor:                 h("#fb4934"),
		InfoColor:                  h("#83a598"),
		SelectionBGColor:           h("#83a598"),
		SelectionFGColor:           h("#282828"),
		InputBGColor:               h("#3c3836"),
		InputFGColor:               h("#ebdbb2"),
		InputPlaceholderColor:      h("#928374"),
		InputCursorColor:           h("#83a598"),
		InputBorderColor:           h("#83a598"),
		BarBGColor:                 h("#3c3836"),
		BarFGColor:                 h("#ebdbb2"),
		FooterBGColor:              h("#1d2021"),
		FooterFGColor:              h("#ebdbb2"),
		FooterMutedColor:           h("#928374"),
		DialogBGColor:              h("#32302f"),
		DialogFGColor:              h("#ebdbb2"),
		DialogBorderColor:          h("#83a598"),
		DialogScrimColor:           h("#1d2021"),
	}
}

func monokaiPro() Theme {
	return &BaseTheme{
		ThemeName:                  "monokai-pro",
		BackgroundColor:            h("#2d2a2e"),
		BackgroundPanelColor:       h("#403e41"),
		BackgroundOverlayColor:     h("#363337"),
		BackgroundInteractiveColor: h("#4a474b"),
		CardChromeColor:            h("#403e41"),
		CardBodyColor:              h("#2d2a2e"),
		CardFrameFGColor:           h("#c1c0c0"),
		CardFocusEdgeColor:         h("#ab9df2"),
		TextColor:                  h("#fcfcfa"),
		TextMutedColor:             h("#727072"),
		TextInverseColor:           h("#2d2a2e"),
		TextAccentColor:            h("#ab9df2"),
		BorderNormalColor:          h("#403e41"),
		BorderSubtleColor:          h("#221f22"),
		BorderFocusColor:           h("#ab9df2"),
		SuccessColor:               h("#a9dc76"),
		WarningColor:               h("#ffd866"),
		ErrorColor:                 h("#ff6188"),
		InfoColor:                  h("#78dce8"),
		SelectionBGColor:           h("#ab9df2"),
		SelectionFGColor:           h("#2d2a2e"),
		InputBGColor:               h("#403e41"),
		InputFGColor:               h("#fcfcfa"),
		InputPlaceholderColor:      h("#727072"),
		InputCursorColor:           h("#ab9df2"),
		InputBorderColor:           h("#ab9df2"),
		BarBGColor:                 h("#403e41"),
		BarFGColor:                 h("#fcfcfa"),
		FooterBGColor:              h("#221f22"),
		FooterFGColor:              h("#fcfcfa"),
		FooterMutedColor:           h("#727072"),
		DialogBGColor:              h("#363337"),
		DialogFGColor:              h("#fcfcfa"),
		DialogBorderColor:          h("#ab9df2"),
		DialogScrimColor:           h("#221f22"),
	}
}

func kanagawa() Theme {
	return &BaseTheme{
		ThemeName:                  "kanagawa",
		BackgroundColor:            h("#1f1f28"),
		BackgroundPanelColor:       h("#2a2a37"),
		BackgroundOverlayColor:     h("#252531"),
		BackgroundInteractiveColor: h("#363646"),
		CardChromeColor:            h("#2a2a37"),
		CardBodyColor:              h("#1f1f28"),
		CardFrameFGColor:           h("#c8c093"),
		CardFocusEdgeColor:         h("#7e9cd8"),
		TextColor:                  h("#dcd7ba"),
		TextMutedColor:             h("#727169"),
		TextInverseColor:           h("#1f1f28"),
		TextAccentColor:            h("#7e9cd8"),
		BorderNormalColor:          h("#2a2a37"),
		BorderSubtleColor:          h("#16161d"),
		BorderFocusColor:           h("#7e9cd8"),
		SuccessColor:               h("#98bb6c"),
		WarningColor:               h("#dca561"),
		ErrorColor:                 h("#e46876"),
		InfoColor:                  h("#7fb4ca"),
		SelectionBGColor:           h("#7e9cd8"),
		SelectionFGColor:           h("#1f1f28"),
		InputBGColor:               h("#2a2a37"),
		InputFGColor:               h("#dcd7ba"),
		InputPlaceholderColor:      h("#727169"),
		InputCursorColor:           h("#7e9cd8"),
		InputBorderColor:           h("#7e9cd8"),
		BarBGColor:                 h("#2a2a37"),
		BarFGColor:                 h("#dcd7ba"),
		FooterBGColor:              h("#16161d"),
		FooterFGColor:              h("#dcd7ba"),
		FooterMutedColor:           h("#727169"),
		DialogBGColor:              h("#252531"),
		DialogFGColor:              h("#dcd7ba"),
		DialogBorderColor:          h("#7e9cd8"),
		DialogScrimColor:           h("#16161d"),
	}
}

func rosePine() Theme {
	return &BaseTheme{
		ThemeName:                  "rose-pine",
		BackgroundColor:            h("#191724"),
		BackgroundPanelColor:       h("#26233a"),
		BackgroundOverlayColor:     h("#1f1d2e"),
		BackgroundInteractiveColor: h("#31748f"),
		CardChromeColor:            h("#26233a"),
		CardBodyColor:              h("#191724"),
		CardFrameFGColor:           h("#e0def4"),
		CardFocusEdgeColor:         h("#9ccfd8"),
		TextColor:                  h("#e0def4"),
		TextMutedColor:             h("#6e6a86"),
		TextInverseColor:           h("#191724"),
		TextAccentColor:            h("#9ccfd8"),
		BorderNormalColor:          h("#26233a"),
		BorderSubtleColor:          h("#12101e"),
		BorderFocusColor:           h("#9ccfd8"),
		SuccessColor:               h("#31748f"),
		WarningColor:               h("#f6c177"),
		ErrorColor:                 h("#eb6f92"),
		InfoColor:                  h("#9ccfd8"),
		SelectionBGColor:           h("#9ccfd8"),
		SelectionFGColor:           h("#191724"),
		InputBGColor:               h("#26233a"),
		InputFGColor:               h("#e0def4"),
		InputPlaceholderColor:      h("#6e6a86"),
		InputCursorColor:           h("#9ccfd8"),
		InputBorderColor:           h("#9ccfd8"),
		BarBGColor:                 h("#26233a"),
		BarFGColor:                 h("#e0def4"),
		FooterBGColor:              h("#12101e"),
		FooterFGColor:              h("#e0def4"),
		FooterMutedColor:           h("#6e6a86"),
		DialogBGColor:              h("#1f1d2e"),
		DialogFGColor:              h("#e0def4"),
		DialogBorderColor:          h("#9ccfd8"),
		DialogScrimColor:           h("#12101e"),
	}
}

func ayuMirage() Theme {
	return &BaseTheme{
		ThemeName:                  "ayu-mirage",
		BackgroundColor:            h("#1f2430"),
		BackgroundPanelColor:       h("#242b38"),
		BackgroundOverlayColor:     h("#212733"),
		BackgroundInteractiveColor: h("#2d3547"),
		CardChromeColor:            h("#242b38"),
		CardBodyColor:              h("#1f2430"),
		CardFrameFGColor:           h("#cbccc6"),
		CardFocusEdgeColor:         h("#5ccfe6"),
		TextColor:                  h("#cbccc6"),
		TextMutedColor:             h("#607080"),
		TextInverseColor:           h("#1f2430"),
		TextAccentColor:            h("#5ccfe6"),
		BorderNormalColor:          h("#242b38"),
		BorderSubtleColor:          h("#171c28"),
		BorderFocusColor:           h("#5ccfe6"),
		SuccessColor:               h("#bae67e"),
		WarningColor:               h("#ffd580"),
		ErrorColor:                 h("#ff3333"),
		InfoColor:                  h("#5ccfe6"),
		SelectionBGColor:           h("#5ccfe6"),
		SelectionFGColor:           h("#1f2430"),
		InputBGColor:               h("#242b38"),
		InputFGColor:               h("#cbccc6"),
		InputPlaceholderColor:      h("#607080"),
		InputCursorColor:           h("#5ccfe6"),
		InputBorderColor:           h("#5ccfe6"),
		BarBGColor:                 h("#242b38"),
		BarFGColor:                 h("#cbccc6"),
		FooterBGColor:              h("#171c28"),
		FooterFGColor:              h("#cbccc6"),
		FooterMutedColor:           h("#607080"),
		DialogBGColor:              h("#212733"),
		DialogFGColor:              h("#cbccc6"),
		DialogBorderColor:          h("#5ccfe6"),
		DialogScrimColor:           h("#171c28"),
	}
}

func oneDark() Theme {
	return &BaseTheme{
		ThemeName:                  "one-dark",
		BackgroundColor:            h("#282c34"),
		BackgroundPanelColor:       h("#3e4451"),
		BackgroundOverlayColor:     h("#353b45"),
		BackgroundInteractiveColor: h("#4b5263"),
		CardChromeColor:            h("#3e4451"),
		CardBodyColor:              h("#282c34"),
		CardFrameFGColor:           h("#abb2bf"),
		CardFocusEdgeColor:         h("#61afef"),
		TextColor:                  h("#abb2bf"),
		TextMutedColor:             h("#5c6370"),
		TextInverseColor:           h("#282c34"),
		TextAccentColor:            h("#61afef"),
		BorderNormalColor:          h("#3e4451"),
		BorderSubtleColor:          h("#21252b"),
		BorderFocusColor:           h("#61afef"),
		SuccessColor:               h("#98c379"),
		WarningColor:               h("#e5c07b"),
		ErrorColor:                 h("#e06c75"),
		InfoColor:                  h("#61afef"),
		SelectionBGColor:           h("#61afef"),
		SelectionFGColor:           h("#282c34"),
		InputBGColor:               h("#3e4451"),
		InputFGColor:               h("#abb2bf"),
		InputPlaceholderColor:      h("#5c6370"),
		InputCursorColor:           h("#61afef"),
		InputBorderColor:           h("#61afef"),
		BarBGColor:                 h("#3e4451"),
		BarFGColor:                 h("#abb2bf"),
		FooterBGColor:              h("#21252b"),
		FooterFGColor:              h("#abb2bf"),
		FooterMutedColor:           h("#5c6370"),
		DialogBGColor:              h("#353b45"),
		DialogFGColor:              h("#abb2bf"),
		DialogBorderColor:          h("#61afef"),
		DialogScrimColor:           h("#21252b"),
	}
}

func materialOcean() Theme {
	return &BaseTheme{
		ThemeName:                  "material-ocean",
		BackgroundColor:            h("#0f111a"),
		BackgroundPanelColor:       h("#1b1e2b"),
		BackgroundOverlayColor:     h("#161822"),
		BackgroundInteractiveColor: h("#292d3e"),
		CardChromeColor:            h("#1b1e2b"),
		CardBodyColor:              h("#0f111a"),
		CardFrameFGColor:           h("#8f93a2"),
		CardFocusEdgeColor:         h("#82aaff"),
		TextColor:                  h("#8f93a2"),
		TextMutedColor:             h("#464b5d"),
		TextInverseColor:           h("#0f111a"),
		TextAccentColor:            h("#82aaff"),
		BorderNormalColor:          h("#1b1e2b"),
		BorderSubtleColor:          h("#090b10"),
		BorderFocusColor:           h("#82aaff"),
		SuccessColor:               h("#c3e88d"),
		WarningColor:               h("#ffcb6b"),
		ErrorColor:                 h("#f07178"),
		InfoColor:                  h("#89ddff"),
		SelectionBGColor:           h("#82aaff"),
		SelectionFGColor:           h("#0f111a"),
		InputBGColor:               h("#1b1e2b"),
		InputFGColor:               h("#8f93a2"),
		InputPlaceholderColor:      h("#464b5d"),
		InputCursorColor:           h("#82aaff"),
		InputBorderColor:           h("#82aaff"),
		BarBGColor:                 h("#1b1e2b"),
		BarFGColor:                 h("#8f93a2"),
		FooterBGColor:              h("#090b10"),
		FooterFGColor:              h("#8f93a2"),
		FooterMutedColor:           h("#464b5d"),
		DialogBGColor:              h("#161822"),
		DialogFGColor:              h("#8f93a2"),
		DialogBorderColor:          h("#82aaff"),
		DialogScrimColor:           h("#090b10"),
	}
}

func githubDark() Theme {
	return &BaseTheme{
		ThemeName:                  "github-dark",
		BackgroundColor:            h("#0d1117"),
		BackgroundPanelColor:       h("#161b22"),
		BackgroundOverlayColor:     h("#131920"),
		BackgroundInteractiveColor: h("#21262d"),
		CardChromeColor:            h("#161b22"),
		CardBodyColor:              h("#0d1117"),
		CardFrameFGColor:           h("#8b949e"),
		CardFocusEdgeColor:         h("#58a6ff"),
		TextColor:                  h("#c9d1d9"),
		TextMutedColor:             h("#484f58"),
		TextInverseColor:           h("#0d1117"),
		TextAccentColor:            h("#58a6ff"),
		BorderNormalColor:          h("#161b22"),
		BorderSubtleColor:          h("#0d1117"),
		BorderFocusColor:           h("#58a6ff"),
		SuccessColor:               h("#3fb950"),
		WarningColor:               h("#d29922"),
		ErrorColor:                 h("#f85149"),
		InfoColor:                  h("#58a6ff"),
		SelectionBGColor:           h("#58a6ff"),
		SelectionFGColor:           h("#0d1117"),
		InputBGColor:               h("#161b22"),
		InputFGColor:               h("#c9d1d9"),
		InputPlaceholderColor:      h("#484f58"),
		InputCursorColor:           h("#58a6ff"),
		InputBorderColor:           h("#58a6ff"),
		BarBGColor:                 h("#161b22"),
		BarFGColor:                 h("#c9d1d9"),
		FooterBGColor:              h("#010409"),
		FooterFGColor:              h("#c9d1d9"),
		FooterMutedColor:           h("#484f58"),
		DialogBGColor:              h("#131920"),
		DialogFGColor:              h("#c9d1d9"),
		DialogBorderColor:          h("#58a6ff"),
		DialogScrimColor:           h("#010409"),
	}
}
